@startuml
title Accounting

actor Бухгалтер

(1.0\nБухгалтерский учёт) as AccountingProc

rectangle ККМ
rectangle "1С Бухгалтерия" as 1cF
rectangle "1С Торговля и склад" as 1cW

database "D1: Файл 1С Бухгалтерия" as 1cF_File
database "D2: Файл 1С Торговля и склад" as 1cW_File


Бухгалтер --> AccountingProc : Доходы, расходы, сотрудники, зарплаты, реквизиты\n PII, FINANCIAL

ККМ --> AccountingProc : Внесение оплаты\n FINANCIAL (Сумма), SERVICES (Услуги)
note on link
 TODO
 Шифровать данные при передаче по сети (TLS)
end note

AccountingProc --> 1cF : Доходы, расходы, сотрудники, зарплаты, реквизиты\n PII, FINANCIAL, SERVICES
1cF --> 1cF_File : Сохранение в файл\n PII, FINANCIAL, SERVICES
note on link
 TODO
 Заменить на клиент-серверный вариант
 Хранить данные на защищённом сервере и делать резервные копии
 Шифровать данные на сервере
 Ограничить доступ к данным в  1С
 Шифровать данные при передаче по сети (TLS)
end note

1cW_File --> 1cW : Чтение данных ТМЦ\n FINANCIAL
note on link
 TODO
 Заменить на клиент-серверный вариант
 Хранить данные на защищённом сервере и делать резервные копии
 Шифровать данные на сервере
 Ограничить доступ к данным в  1С
 Шифровать данные при передаче по сети (TLS)
end note
1cW --> AccountingProc : Данные ТМЦ\n FINANCIAL

@enduml
