@startuml
title Client Registration

actor Администратор
actor Клиент

(1.0\nРегистрация клиента) as RegisterProc

rectangle Excel
rectangle Сканер
rectangle "Файловый сервер" as fileServer
rectangle Архив

database "D1: Список Пациентов Excel" as xlsx
database "D2: Файлы пациента" as patientFiles
database "D3: Бумажные оригиналы документов" as patientDocs

Клиент --> Администратор : Персональные данные, расширенная форма, согласие на обработку ПД\n PII, MEDICAL (Хронические заболевания)
note on link
 TODO
 Использовать минимизацию собираемых данных
 Шифровать данные при передаче для электронных документов (TLS)
end note
Администратор --> RegisterProc : Данные и документы клиента\n PII, MEDICAL (Хронические заболевания)

RegisterProc --> Сканер : Документы клиента\n PII, MEDICAL (Хронические заболевания)
Сканер --> fileServer : Сканы документов\n PII, MEDICAL (Хронические заболевания)
note on link
 TODO
 Шифровать данные при передаче по сети (TLS)
 Тегировать данные
end note
fileServer --> patientFiles : Сканы документов\n PII, MEDICAL (Хронические заболевания)
note on link
 TODO
 Заменить хранение в файловой системе с общим доступом
    на хранилище с контролем доступа или МИС
 Хранить данные в шифрованном виде
 Бекапировать данные
 Вести историю версий файлов и журнал изменений
end note

RegisterProc --> Excel : Данные пациента\n PII, MEDICAL (Хронические заболевания)
note on link
 TODO
 Заменить Excel Медицинской Информационной Системой
    Что обеспечит контроль и аудит доступа, шифрование, отслеживание изменений
    Настроить в МИС политики доступа, авторизацию
 Шифровать данные при передаче по сети (TLS)
end note
Excel --> fileServer : Сохранение в файл xlsx\n PII, MEDICAL (Хронические заболевания)
fileServer --> xlsx : Сохранение в файл xlsx\n PII, MEDICAL (Хронические заболевания)

RegisterProc --> Архив : Оригиналы документов (согласие, форма)\n PII, MEDICAL (Хронические заболевания)
note on link
 TODO
 Тегировать документы, ограничить доступ основываясь на тегах
end note
Архив --> patientDocs : Оригиналы документов (согласие, форма)\n PII, MEDICAL (Хронические заболевания)
note on link
 TODO
 Определить процедуры хранения и уничтожения документов с учётом тегов
end note

@enduml
