@startuml
title Laboratory Analysis Process

actor Клиент
actor Врач
actor "Сотрудник лаборатории" as LabEmployee

(1.0\nНазначение и обработка анализов) as LabProc

rectangle Excel
rectangle "Файловый сервер" as fileServer
rectangle "Лабораторная система" as labSystem

database "D1: Реестр анализов Excel" as xlsx
database "D2: Файлы пациента" as patientFiles


Клиент --> Врач : Жалобы\nPII, MEDICAL (Жалобы)
Врач --> LabProc : Назначение анализов\nPII, MEDICAL (Назначения)

LabProc --> Excel : Назначение анализов\nPII, MEDICAL (Назначения)
note on link
 TODO
 Заменить Excel Медицинской Информационной Системой
    Что обеспечит контроль и аудит доступа, шифрование, отслеживание изменений
 Настроить в МИС доступ врача только к анализам текущего пациента
 Шифровать данные при передаче по сети (TLS)
end note
Excel --> fileServer : Сохранение файла реестра анализов в xlsx\nPII, MEDICAL (Назначения)
fileServer --> xlsx : Сохранение файла реестра анализов в xlsx\nPII, MEDICAL (Назначения)

LabProc --> labSystem : Назначение анализов\nPII, MEDICAL (Назначения)
note on link
 TODO
 Шифровать данные при передаче по сети (TLS)
 Вести журналирование запросов и ответов
 Аутентификация и авторизация доступа
    Доступ только к данным, передаваемым в лабораторию
 Ограничить передаваемые в лабораторную систему данные
    Использовать токенизацию или псевдонимизацию PII
end note
LabEmployee --> labSystem : Результаты анализов\nPII, MEDICAL (Результаты)
labSystem --> fileServer : Результаты анализов\nPII, MEDICAL (Результаты)
note on link
 TODO
 Шифровать данные при передаче по сети (TLS)
 Вести журналирование запросов и ответов
 Тегировать полученные от лаборатории данные
 Доступ только на добавление данных, без чтения/удаления/обновления
 Хранить полученные от лаборатории данные
    либо в МИС используя механизмы защиты данных МИС
    либо в шифрованном виде в хранилище с контролем доступа
end note
fileServer --> patientFiles : Результаты анализов\nPII, MEDICAL (Результаты)

@enduml